spring.application.name=Summer
spring.datasource.url = jdbc:mysql://localhost:3306/summer?serverTimezone=UTC
spring.datasource.username = root
spring.datasource.password =
spring.jpa.hibernate.ddl-auto = update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#http://localhost:8080/swagger-ui/index.html#